version: '3.7'
services:
        account-service:
                image: wrusselly/account-service
                depends_on:
                        - mongo-service
                        - secret-service
        aes-encryption-service:
                image: wrusselly/aes-encryption-service
        authentication-client:
                image: wrusselly/authentication-client
        authentication-service:
                image: wrusselly/authentication-service
                environment:
                        - ACTIVATION_LINK=http://${ACTIVATION_IP}/authentication/api/activate
        dashboard-client:
                image: wrusselly/dashboard-client 
        dashboard-service:
                image: wrusselly/dashboard-service 
                depends_on:
                        - account-service
                        - session-token-service
        email-service: 
                image: wrusselly/email-service 
                depends_on:
                        - aes-encryption-service
                environment:
                        - GMAIL_USER=ilovedocker123@gmail.com
                        - GMAIL_PASS=ilovedocker1!
                        - SERVICE_NAME="CI project"

        gateway: 
                image: wrusselly/gateway 
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                depends_on:
                        - dashboard-client
                        - authentication-client
                        - authentication-service
                        - dashboard-service
        group-service: 
                image: wrusselly/group-service 
        mongo-service: 
                image: wrusselly/mongo-service  
                depends_on:
                        - mongo
        role-service: 
                image: wrusselly/role-service
        secret-service: 
                image: wrusselly/secret-service 
                depends_on:
                        - mongo-service
        session-token-service: 
                image: wrusselly/session-token-service 
                depends_on:
                        - mongo-service
                        - aes-encryption-service
        mongo:
                image: mongo 



